'use client';

import Link from 'next/link';
import React, { useEffect, useMemo, useState } from 'react';
import { getAccountabilityAccountByUserId, listAccountabilityAccounts } from '@/entities/accountability/api/accountability-client';
import { listApprovalRequests } from '@/entities/approval/api/approval-client';
import { listCandidates } from '@/entities/candidate/api/candidate-client';
import { listEmployees } from '@/entities/employee/api/employee-client';
import { getTodayDailyReport, getTodayObjectAttendance } from '@/entities/object/api/object-operations-client';
import { listObjects } from '@/entities/object/api/object-client';
import type { ServiceObject } from '@/entities/object/model/object.types';
import { listOneTimeOrders } from '@/entities/one-time-order/api/one-time-order-client';
import type { OneTimeOrderListItem } from '@/entities/one-time-order/model/one-time-order.types';
import { listTasks } from '@/entities/task/api/task-client';
import type { TaskItem } from '@/entities/task/model/task.types';
import { useAuth } from '@/shared/auth/use-auth';
import { getUserDisplayName } from '@/shared/lib/display-name';
import styles from './dashboard-workspace-v2.module.css';

type Attention={id:string;href:string;badge:string;tone:'danger'|'warning'|'neutral';title:string;subtitle:string;date:string};
type Signals=Record<string,{attendanceMissing:boolean;dailyReportMissing:boolean}>;
type Data={approvals:any[];tasks:any;objects:ServiceObject[];orders:any;employees:any;unassigned:number;overdueCandidates:number;money:{submitted:number;closures:number;receiptCount:number;receiptAmount:number};signals:Signals};
const EMPTY={items:[],page:1,limit:0,total:0,totalPages:0};
const LIMIT=5,EXPANDED=14;

function now(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const g=(x:string)=>p.find(i=>i.type===x)?.value??'0';return{date:`${g('year')}-${g('month')}-${g('day')}`,minutes:+g('hour')*60+ +g('minute')}}
function day(v:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(v)}
function date(v:string|null){return v?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'short'}).format(new Date(v)):'Без срока'}
function greet(){const h=Math.floor(now().minutes/60);return h<6?'Доброй ночи':h<12?'Доброе утро':h<18?'Добрый день':'Добрый вечер'}
function mine(t:TaskItem,id?:string){return Boolean(t.myAssignment||t.assignees.some(a=>a.id===id&&a.isActive))}
function taskTime(t:TaskItem){if(t.isOverdue)return t.dueAt?`до ${date(t.dueAt)}`:'Просрочено';if(!t.dueAt)return'Без срока';const k=day(new Date(t.dueAt));if(k===now().date)return'Сегодня';const x=new Date();x.setDate(x.getDate()+1);return k===day(x)?'Завтра':date(t.dueAt)}
function rank(t:TaskItem,id?:string){const m=mine(t,id),today=Boolean(t.dueAt&&day(new Date(t.dueAt))===now().date);if(m&&t.isOverdue)return 0;if(m&&today)return 1;if(m&&t.dueAt)return 2;if(m)return 3;if(t.isOverdue)return 4;return 5}
function money(v:number){return`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v)} ₽`}
function orderDate(i:OneTimeOrderListItem){if(!i.executionStartDate)return'Без даты';const k=i.executionStartDate.slice(0,10);return k===now().date?'Сегодня':k<now().date?`Просрочен · ${date(i.executionStartDate)}`:date(i.executionStartDate)}

export function DashboardWorkspaceV2():React.JSX.Element{
 const{user}=useAuth();
 const[data,setData]=useState<Data>({approvals:[],tasks:EMPTY,objects:[],orders:EMPTY,employees:{...EMPTY,capabilities:{canCreate:false}},unassigned:0,overdueCandidates:0,money:{submitted:0,closures:0,receiptCount:0,receiptAmount:0},signals:{}});
 const[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[attentionExpanded,setAttentionExpanded]=useState(false),[tasksExpanded,setTasksExpanded]=useState(false);
 useEffect(()=>{let alive=true;const safe=<T,>(p:Promise<T>,f:T)=>p.catch(()=>f);const load=async()=>{setLoading(true);setFailed(false);try{const [approvals,tasks,objects,orders,employees,unassigned,candidates]=await Promise.all([safe(listApprovalRequests({status:'pending'}),[]),safe(listTasks({page:1,limit:60,sortBy:'dueAt',sortDirection:'asc'}),EMPTY as any),safe(listObjects(),[]),safe(listOneTimeOrders({page:1,limit:20,sortBy:'executionStartDate',sortDirection:'asc'}),EMPTY as any),safe(listEmployees({archiveState:'active',page:1,limit:1}),{...EMPTY,capabilities:{canCreate:false}} as any),safe(listEmployees({archiveState:'active',hasActiveObjectAssignment:false,page:1,limit:1}),{...EMPTY,capabilities:{canCreate:false}} as any),user?.capabilities?.canAccessCandidates?safe(listCandidates({slaState:'overdue',archiveState:'active',page:1,limit:1}),EMPTY as any):Promise.resolve(EMPTY)]);
 let submitted=0,closures=0,receiptCount=0,receiptAmount=0;if(user?.capabilities?.canReviewAccountability){const accounts=await safe(listAccountabilityAccounts(),[]);submitted=accounts.reduce((s,a)=>s+a.summary.submittedExpensesCount,0);closures=accounts.filter(a=>a.status==='closing_requested').length;const details=await Promise.all(accounts.map(a=>safe(getAccountabilityAccountByUserId(a.user.id),null)));const receipts=details.flatMap(d=>d?.fundings??[]).filter(f=>f.fundingType==='one_time_order_receipt'&&f.entryDirection==='credit');receiptCount=receipts.length;receiptAmount=receipts.reduce((s,f)=>s+Number(f.amount),0)}
 const active=(objects as ServiceObject[]).filter(o=>o.status==='active'),attendanceRequired=now().minutes>=510,reportRequired=now().minutes>=1020;const entries=await Promise.all(active.map(async o=>{const[a,r]=await Promise.all([attendanceRequired?safe(getTodayObjectAttendance(o.id),null):null,reportRequired?safe(getTodayDailyReport(o.id),null):null]);return[o.id,{attendanceMissing:attendanceRequired&&a!==null&&a.employeeIds.length===0,dailyReportMissing:reportRequired&&r===null}] as const}));if(alive)setData({approvals,tasks,objects,orders,employees,unassigned:unassigned.total,overdueCandidates:candidates.total,money:{submitted,closures,receiptCount,receiptAmount},signals:Object.fromEntries(entries)})}catch{if(alive)setFailed(true)}finally{if(alive)setLoading(false)}};void load();return()=>{alive=false}},[user?.capabilities?.canAccessCandidates,user?.capabilities?.canReviewAccountability]);
 const active=useMemo(()=>data.objects.filter(o=>o.status==='active'),[data.objects]);const attendance=active.filter(o=>data.signals[o.id]?.attendanceMissing).length,reports=active.filter(o=>data.signals[o.id]?.dailyReportMissing).length;const problems=active.filter(o=>!o.responsible||o.employees.length===0||data.signals[o.id]?.attendanceMissing||data.signals[o.id]?.dailyReportMissing);const objects=[...problems,...active.filter(o=>!problems.some(p=>p.id===o.id))].slice(0,4);
 const tasks=useMemo(()=>[...data.tasks.items].filter((t:TaskItem)=>!['completed','cancelled'].includes(t.status)).sort((a:TaskItem,b:TaskItem)=>rank(a,user?.id)-rank(b,user?.id)||(a.dueAt?+new Date(a.dueAt):Number.MAX_SAFE_INTEGER)-(b.dueAt?+new Date(b.dueAt):Number.MAX_SAFE_INTEGER)),[data.tasks.items,user?.id]);
 const attentionRows:Attention[]=[...(attendance?[{id:'attendance',href:'/objects?status=active&issue=attendance_missing',badge:'Объекты',tone:'warning' as const,title:'Нет отметки присутствия',subtitle:`${attendance} объектов не отмечены за рабочий день`,date:'Сегодня'}]:[]),...(reports?[{id:'reports',href:'/objects?status=active&issue=daily_report_missing',badge:'Отчёт',tone:'warning' as const,title:'Нет дневного отчёта',subtitle:`${reports} объектов без отчёта после 17:00`,date:'Сегодня'}]:[]),...data.tasks.items.filter((t:TaskItem)=>t.isOverdue&&t.status!=='completed').map((t:TaskItem)=>({id:`t-${t.id}`,href:`/tasks/${t.id}`,badge:'Просрочено',tone:'danger' as const,title:t.title,subtitle:t.targetName||'Без привязки',date:taskTime(t)})),...data.approvals.map((a:any)=>({id:`a-${a.id}`,href:`/approvals?status=pending&sourceEntityType=${a.sourceEntityType}&sourceEntityId=${a.sourceEntityId}`,badge:'Согласование',tone:'warning' as const,title:a.summary.title,subtitle:a.summary.subtitle??'Ожидает решения',date:date(a.createdAt)})),...data.tasks.items.filter((t:TaskItem)=>t.status==='awaiting_confirmation'&&!t.isOverdue).map((t:TaskItem)=>({id:`c-${t.id}`,href:`/tasks/${t.id}`,badge:'Подтверждение',tone:'neutral' as const,title:t.title,subtitle:t.targetName||'Без привязки',date:taskTime(t)}))];
 const visibleAttention=attentionRows.slice(0,attentionExpanded?EXPANDED:LIMIT),visibleTasks=tasks.slice(0,tasksExpanded?EXPANDED:LIMIT),orders=[...data.orders.items].filter((o:any)=>!['completed','cancelled'].includes(o.status)).sort((a:any,b:any)=>(a.executionStartDate??'9999').localeCompare(b.executionStartDate??'9999')).slice(0,3),todayOrders=data.orders.items.filter((o:any)=>o.executionStartDate?.slice(0,10)===now().date&&!['completed','cancelled'].includes(o.status)).length,assignments=active.reduce((s,o)=>s+o.employees.length,0),decisions=data.approvals.length+data.money.submitted+data.money.closures,count=attentionRows.length,name=user?getUserDisplayName(user).trim().split(/\s+/)[0]:'';
 return <div className={styles.root}><section className={styles.intro}><div className={styles.introCopy}><div className={styles.greeting}>{greet()}{name?`, ${name}`:''}</div><div className={styles.summary}>{loading?'Обновляем рабочую сводку…':count?`На сегодня ${count} вопросов требуют внимания`:'На сегодня срочных вопросов нет'}</div></div><div className={styles.health}><i className={`${styles.dot} ${count?styles.attentionDot:''}`}/>{loading?'Обновление':count?'Есть приоритеты':'Спокойный контур'}</div></section>{failed?<div className={styles.notice}>Часть данных рабочего стола временно недоступна.</div>:null}
 <section className={styles.today}><div className={styles.todayLabel}>Сегодня</div><Link className={styles.todayItem} href="/objects?status=active"><strong>{loading?'—':active.length}</strong><span>объектов</span></Link><Link className={styles.todayItem} href="/employees?archiveState=active&hasActiveObjectAssignment=true"><strong>{loading?'—':assignments}</strong><span>назначений на объекты</span></Link><Link className={styles.todayItem} href="/objects?status=active&issue=attendance_missing"><strong>{loading?'—':attendance}</strong><span>без отметки присутствия</span></Link><Link className={styles.todayItem} href={`/one-time-orders?dateFrom=${now().date}&dateTo=${now().date}&sortBy=executionStartDate&sortDirection=asc`}><strong>{loading?'—':todayOrders}</strong><span>разовых сегодня</span></Link><Link className={styles.todayItem} href="/approvals?status=pending"><strong>{loading?'—':decisions}</strong><span>решений от вас</span></Link></section>
 <div className={styles.grid}><div className={styles.column}><section className={styles.panel}><header className={styles.head}><div className={styles.headTitle}><h2>Требует внимания</h2><span className={styles.count}>{count}</span></div>{attentionRows.length>LIMIT?<button className={styles.headButton} onClick={()=>setAttentionExpanded(v=>!v)}>{attentionExpanded?'Свернуть':`Ещё ${attentionRows.length-LIMIT}`}</button>:null}</header><div className={styles.rows}>{visibleAttention.map(i=><Link className={`${styles.row} ${styles.attentionRow}`} href={i.href} key={i.id}><span className={`${styles.badge} ${styles[i.tone]}`}>{i.badge}</span><span className={styles.rowCopy}><strong>{i.title}</strong><small>{i.subtitle}</small></span><span className={styles.meta}>{i.date}</span></Link>)}</div></section>
 <section className={styles.panel}><header className={styles.head}><div className={styles.headTitle}><h2>Объекты</h2>{problems.length?<span className={styles.count}>{problems.length}</span>:null}</div><Link href={problems.length?'/objects?status=active&issue=attention':'/objects?status=active'}>Проблемные →</Link></header><div className={styles.sectionSummary}><strong>{loading?'—':active.length}</strong><span>активных</span><span>{problems.length?`${problems.length} требуют внимания`:'Проблем не обнаружено'}</span></div><div className={styles.rows}>{objects.map(o=><Link className={`${styles.row} ${styles.objectRow}`} href={`/objects/${o.id}`} key={o.id}><span className={styles.rowCopy}><strong>{o.name}</strong><small>{o.address}</small></span><span className={styles.meta}>{o.responsible?.fullName??'Нет ответственного'}</span><span className={styles.meta}>{o.employees.length} чел.</span></Link>)}</div></section></div>
 <div className={styles.column}><section className={styles.panel}><header className={styles.head}><div className={styles.headTitle}><h2>Мои задачи</h2><span className={styles.count}>{tasks.length}</span></div><div className={styles.headActions}>{tasks.length>LIMIT?<button className={styles.headButton} onClick={()=>setTasksExpanded(v=>!v)}>{tasksExpanded?'Свернуть':`Ещё ${tasks.length-LIMIT}`}</button>:null}<Link href="/tasks?mode=assigned&sortBy=dueAt&sortDirection=asc">В реестр →</Link></div></header><div className={styles.rows}>{visibleTasks.map((t:TaskItem)=>{const m=mine(t,user?.id),today=Boolean(t.dueAt&&day(new Date(t.dueAt))===now().date);return <Link className={`${styles.row} ${styles.taskRow}`} href={`/tasks/${t.id}`} key={t.id}><span className={`${styles.badge} ${t.isOverdue?styles.danger:today?styles.warning:styles.neutral}`}>{t.isOverdue?'Просрочено':today?'Сегодня':m?'Назначено':'Компания'}</span><span className={styles.rowCopy}><strong>{t.title}</strong><small>{t.targetName||'Без привязки'}</small></span><span className={styles.taskTime}>{taskTime(t)}</span></Link>})}</div></section>
 {user?.capabilities?.canAccessAccountability?<section className={styles.panel}><header className={styles.head}><div className={styles.headTitle}><h2>Деньги</h2>{data.money.submitted+data.money.closures?<span className={styles.count}>{data.money.submitted+data.money.closures}</span>:null}</div><Link href="/accountability">Подотчёт →</Link></header><div className={styles.finance}><Link href="/accountability?view=submitted-expenses" className={styles.financeItem}><span>Расходы на проверке</span><strong>{loading?'—':data.money.submitted}</strong><small>ожидают решения</small></Link><Link href="/accountability?view=closing-requested" className={styles.financeItem}><span>Закрытие подотчёта</span><strong>{loading?'—':data.money.closures}</strong><small>ждут решения</small></Link><Link href="/accountability?view=one-time-receipts" className={styles.financeItem}><span>Приход по разовым</span><strong>{loading?'—':money(data.money.receiptAmount)}</strong><small>{data.money.receiptCount} поступлений</small></Link></div></section>:null}
 <section className={styles.panel}><header className={styles.head}><div className={styles.headTitle}><h2>Разовые заказы</h2></div><Link href="/one-time-orders?sortBy=executionStartDate&sortDirection=asc">Срочные сначала →</Link></header><div className={styles.rows}>{orders.map((o:any)=><Link className={`${styles.row} ${styles.orderRow}`} href={`/one-time-orders/${o.id}`} key={o.id}><span className={styles.rowCopy}><strong>{o.title}</strong><small>{o.linkedObject?.name??o.executionAddress}</small></span><span className={styles.meta}>{o.status}</span><span className={styles.meta}>{orderDate(o)}</span></Link>)}</div></section>
 <section className={styles.panel}><header className={styles.head}><div className={styles.headTitle}><h2>Люди</h2></div><Link href="/employees?archiveState=active">Все →</Link></header><div className={styles.people}><Link href="/employees?archiveState=active" className={styles.peopleItem}><strong>{loading?'—':data.employees.total}</strong><span>активных сотрудников</span></Link><Link href="/employees?archiveState=active&hasActiveObjectAssignment=false" className={styles.peopleItem}><strong>{loading?'—':data.unassigned}</strong><span>без объекта</span></Link>{user?.capabilities?.canAccessCandidates?<Link href="/candidates?archiveState=active&slaState=overdue" className={styles.peopleItem}><strong>{loading?'—':data.overdueCandidates}</strong><span>кандидатов с просроченным SLA</span></Link>:<div className={styles.peopleItem}><strong>—</strong><span>кандидаты недоступны</span></div>}</div></section></div></div></div>;
}
