'use client';

import Link from 'next/link';
import React, { useEffect, useState } from 'react';

import { addCandidateResponse, assignCandidateManager, changeCandidateStatus, getCandidate, listCandidateManagers, setCandidateArchive, updateCandidate } from '@/entities/candidate/api/candidate-client';
import { CANDIDATE_STATUS_OPTIONS, CANDIDATE_TYPE_OPTIONS, candidateSlaLabel, candidateStatusLabel, candidateTypeLabel } from '@/entities/candidate/lib/candidate-presentation';
import type { CandidateCard, CandidateStatus, CandidateType } from '@/entities/candidate/model/candidate.types';
import { PageTitle } from '@/shared/ui/page-title/page-title';
import { SearchableSelect, type SearchableSelectOption } from '@/shared/ui/searchable-select/searchable-select';

export default function CandidatePage({ params }: { params: Promise<{ id: string }> }): React.JSX.Element {
  const [candidate, setCandidate] = useState<CandidateCard | null>(null);
  const [manager, setManager] = useState<SearchableSelectOption | null>(null);
  const [responseText, setResponseText] = useState('');
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ fullName: '', phone: '', comment: '', candidateType: 'regular' as CandidateType });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { let active = true; void params.then(({ id }) => getCandidate(id)).then((item) => { if (active) { setCandidate(item); setForm({ fullName: item.fullName, phone: item.phone ?? '', comment: item.comment ?? '', candidateType: item.candidateType }); } }).catch(() => { if (active) setError('Не удалось загрузить кандидата.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [params]);
  const apply = (next: CandidateCard): void => { setCandidate(next); setForm({ fullName: next.fullName, phone: next.phone ?? '', comment: next.comment ?? '', candidateType: next.candidateType }); };
  const mutate = async (operation: () => Promise<CandidateCard>): Promise<void> => { setSaving(true); setError(null); try { apply(await operation()); } catch { setError('Не удалось сохранить изменение. Обновите карточку и повторите.'); } finally { setSaving(false); } };

  if (loading) return <><PageTitle title="Кандидат" /><div className="page-card">Загрузка...</div></>;
  if (!candidate) return <><PageTitle title="Кандидат" /><div className="page-card inline-notice inline-notice--warning">{error ?? 'Кандидат не найден.'}</div></>;
  const current = candidate.currentAssignment;
  return <><PageTitle title={candidate.fullName} /><div className="page-stack candidate-card-page">
    <div className="action-row"><Link href="/candidates">К реестру</Link>{candidate.deletedAt ? <span className="status-pill">В архиве</span> : null}</div>
    {error ? <div className="page-card inline-notice inline-notice--warning">{error}</div> : null}
    <section className="page-card candidate-summary"><div><span className="detail-label">Телефон</span><strong>{candidate.phone ?? 'Не указан'}</strong></div><div><span className="detail-label">Тип</span><strong>{candidateTypeLabel(candidate.candidateType)}</strong></div><div><span className="detail-label">Статус</span><strong>{candidateStatusLabel(candidate.status)}</strong></div><div><span className="detail-label">SLA</span><span className={`candidate-sla candidate-sla--${candidate.slaState}`}>{candidateSlaLabel(candidate.slaState, current?.responseDueAt)}</span></div></section>
    <section className="candidate-detail-grid"><div className="page-card"><div className="section-header"><div className="section-title">Контактные данные</div>{candidate.capabilities.canManage ? <button type="button" className="button-secondary" onClick={() => setEditing((value) => !value)}>{editing ? 'Отмена' : 'Редактировать'}</button> : null}</div>{editing ? <form className="candidate-form" onSubmit={(event) => { event.preventDefault(); void mutate(() => updateCandidate(candidate.id, { expectedVersion: candidate.version, fullName: form.fullName, phone: form.phone || null, comment: form.comment || null, candidateType: form.candidateType })).then(() => setEditing(false)); }}><label><span>ФИО</span><input required value={form.fullName} onChange={(event) => setForm((value) => ({ ...value, fullName: event.target.value }))} /></label><label><span>Телефон</span><input value={form.phone} onChange={(event) => setForm((value) => ({ ...value, phone: event.target.value }))} /></label><SearchableSelect label="Тип" value={form.candidateType} options={CANDIDATE_TYPE_OPTIONS} clearable={false} onChange={(value) => setForm((currentForm) => ({ ...currentForm, candidateType: value as CandidateType }))} /><label className="candidate-form__wide"><span>Комментарий</span><textarea rows={4} value={form.comment} onChange={(event) => setForm((value) => ({ ...value, comment: event.target.value }))} /></label><button type="submit" disabled={saving}>Сохранить</button></form> : <div className="candidate-comment">{candidate.comment || 'Комментарий не указан.'}</div>}</div>
      <div className="page-card"><div className="section-title">Текущий менеджер</div>{current ? <div className="candidate-current-manager"><strong>{current.manager.fullName}</strong><span className="page-muted">Назначен {new Date(current.assignedAt).toLocaleString('ru-RU')}</span><span className="page-muted">Ответ до {new Date(current.responseDueAt).toLocaleString('ru-RU')}</span></div> : <div className="page-muted">Менеджер не назначен.</div>}{candidate.capabilities.canManage && !candidate.deletedAt && !['accepted', 'rejected'].includes(candidate.status) ? <div className="candidate-manager-control"><SearchableSelect label="Назначить / переназначить" value={manager?.value ?? ''} selectedOption={manager} options={[]} placeholder="Выберите менеджера" onChange={(value) => { if (!value) { setManager(null); return; } void listCandidateManagers({ selectedId: value }).then(([item]) => setManager(item ? { value: item.id, label: item.fullName || item.login, searchText: item.login } : null)); }} asyncSearch={async (value) => (await listCandidateManagers({ q: value })).map((item) => ({ value: item.id, label: item.fullName || item.login, searchText: item.login }))} /><button type="button" disabled={!manager || saving} onClick={() => manager && void mutate(() => assignCandidateManager(candidate.id, manager.value, candidate.version)).then(() => setManager(null))}>Назначить</button></div> : null}</div>
    </section>
    {candidate.capabilities.canManage ? <section className="page-card candidate-actions"><SearchableSelect label="Статус" value={candidate.status} options={CANDIDATE_STATUS_OPTIONS} clearable={false} onChange={(value) => void mutate(() => changeCandidateStatus(candidate.id, value as CandidateStatus, candidate.version))} /><div className="action-row">{candidate.capabilities.canArchive ? <button type="button" className="button-danger" disabled={saving} onClick={() => window.confirm('Архивировать кандидата?') && void mutate(() => setCandidateArchive(candidate.id, candidate.version))}>Архивировать</button> : null}{candidate.capabilities.canRestore ? <button type="button" disabled={saving} onClick={() => void mutate(() => setCandidateArchive(candidate.id, candidate.version, true))}>Восстановить</button> : null}</div></section> : null}
    <section className="candidate-detail-grid"><div className="page-card"><div className="section-title">Ответы менеджеров</div>{candidate.responses.length ? <div className="candidate-history">{candidate.responses.map((response) => <article key={response.id}><div><strong>{response.author.fullName}</strong><time>{new Date(response.createdAt).toLocaleString('ru-RU')}</time></div><p>{response.text}</p></article>)}</div> : <div className="page-muted">Ответов пока нет.</div>}{candidate.capabilities.canRespond ? <form className="candidate-response-form" onSubmit={(event) => { event.preventDefault(); const text = responseText.trim(); if (!text) return; void mutate(() => addCandidateResponse(candidate.id, text)).then(() => setResponseText('')); }}><label><span>Ответ менеджера</span><textarea rows={3} required value={responseText} onChange={(event) => setResponseText(event.target.value)} /></label><button type="submit" disabled={saving || !responseText.trim()}>Добавить ответ</button></form> : null}</div>
      <div className="page-card"><div className="section-title">История назначений</div>{candidate.assignments.length ? <div className="candidate-history">{candidate.assignments.map((assignment) => <article key={assignment.id}><div><strong>{assignment.manager.fullName}</strong><time>{new Date(assignment.assignedAt).toLocaleString('ru-RU')}</time></div><p>Назначил: {assignment.assignedBy.fullName}</p><p>{assignment.firstRespondedAt ? `Ответ: ${new Date(assignment.firstRespondedAt).toLocaleString('ru-RU')}` : 'Ответ не получен'}{assignment.endedAt ? ` · Завершено ${new Date(assignment.endedAt).toLocaleString('ru-RU')}` : ''}</p></article>)}</div> : <div className="page-muted">Назначений пока нет.</div>}</div></section>
  </div></>;
}
